# https://eslint.org/docs/rules/
# https://eslint.org/docs/user-guide/configuring#specifying-environments
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended' # https://github.com/yannickcr/eslint-plugin-react#configuration
plugins:
  - 'babel'
  - 'react'
settings:
  react:
    version: 'detect'
parser: 'babel-eslint'
parserOptions:
  # ecmaVersion: 2018
  # ecmaVersion: 7
  # ecmaVersion: 5
  sourceType: module
  # files:
  #   -
  #     patterns: '**/*.jsx'
rules:
  no-debugger: warn
  no-console: warn
  # no-console: 0 # DEBUG?
  # no-const-assign: error
  # no-unused-vars: 0 # DEBUG?
  no-unused-vars:
    - warn
    -
      vars: local
      varsIgnorePattern: ^_
  # camelcase:
  #   - warn
  # indent:
  #   - warn
  #   - 2
  linebreak-style:
    - error
    - unix
  # quotes:
  #   - warn
  #   - single
  curly: # single line statements without curly braces
    - warn
    # - always
  # curly: 0
  semi: # end-linbe semicolons
    - warn
    - always
  # semi: 0
globals:
  System: true # Webpack dynamic import
  # fetch: true
overrides:
  -  # JS
    files: '**/*.{js,jsx}'
    env:
      browser: true
      commonjs: true
      es6: true
      # node: true
      # jquery: true
